version: '3.8'

networks:
  moneyapp_network:
    name: moneyapp_network

services:
  moneyapp_postgres:
    image : postgres:16.1
    container_name: moneyapp_postgres_db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: moneyapp
    volumes:
      # - /etc/timezone:/etc/timezone:rw
      # - /etc/localtime:/etc/localtime:rw
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: unless-stopped
    networks:
      - moneyapp_network

  moneyapp_redis: 
    image : redis:7.2.4
    container_name: moneyapp_redis
    volumes:
      # - /etc/timezone:/etc/timezone:rw
      # - /etc/localtime:/etc/localtime:rw
      - ./redis:/data
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - moneyapp_network
    depends_on:
      - moneyapp_postgres

  moneyapp_backend:
    image : moneyapp_backend
    container_name: moneyapp_backend
    build:
      context: ./
      dockerfile: backend.dockerfile
    volumes:
      - ./backend:/var/www
      - /var/www/node_modules
      # - /etc/timezone:/etc/timezone:rw
      # - /etc/localtime:/etc/localtime:rw
    ports:
      - 3333:3333
    networks:
      - moneyapp_network
    environment:
      - CHOKIDAR_USEPOLLING=1
      - CHOKIDAR_INTERVAL=6000
    depends_on:
      - moneyapp_postgres
      - moneyapp_redis

  moneyapp_frontend:
    image : moneyapp_frontend
    container_name: moneyapp_frontend
    build:
      context: ./
      dockerfile: frontend.dockerfile
    volumes:
       - ./frontend:/var/www
       - /var/www/node_modules
      # - /etc/timezone:/etc/timezone:rw
      # - /etc/localtime:/etc/localtime:rw
    ports:
      - 3000:3000
    networks:
      - moneyapp_network
    environment:
      - CHOKIDAR_USEPOLLING=1
    depends_on:
      - moneyapp_postgres
      - moneyapp_redis
      - moneyapp_backend