version: '3.8'

networks:
  moneyapp_network:
    name: moneyapp_network
    driver: bridge

services:
  moneyapp_postgres:
    image: postgres:16.1
    container_name: moneyapp_postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_MULTIPLE_DATABASES: moneyapp,moneyappdev,moneyapptest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgre-init.sh:/docker-entrypoint-initdb.d/postgre-init.sh
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - moneyapp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  moneyapp_redis:
    image: redis:7.2.4
    container_name: moneyapp_redis
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - moneyapp_network
    depends_on:
      moneyapp_postgres:
        condition: service_healthy

  moneyapp_backend:
    image: moneyapp_backend
    # cpus: 2
    container_name: moneyapp_backend
    build:
      context: ./
      dockerfile: backend.dockerfile
    volumes:
      - ./backend:/var/www
      - /var/www/node_modules
      - ./npmCacheBackend:/root/.npm
    ports:
      - 3333:3333
      - 4444:4444
    networks:
      - moneyapp_network
    environment:
      - CHOKIDAR_USEPOLLING=1
      - CHOKIDAR_INTERVAL=6000
    depends_on:
      moneyapp_postgres:
        condition: service_healthy
      moneyapp_redis:
        condition: service_started

  moneyapp_frontend:
    image: moneyapp_frontend
    container_name: moneyapp_frontend
    build:
      context: ./
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend:/var/www
      - /var/www/node_modules
      - ./npmCacheFrontend:/root/.npm
    ports:
      - 3000:3000
    networks:
      - moneyapp_network
    environment:
      - CHOKIDAR_USEPOLLING=1
    depends_on:
      - moneyapp_postgres
      - moneyapp_redis
      - moneyapp_backend

  moneyapp_nginx:
    image: nginx
    container_name: moneyapp_nginx
    restart: unless-stopped
    build:
      context: ./
      dockerfile: nginx.dockerfile
    ports:
      - 8888:80
    networks:
      - moneyapp_network
    depends_on:
      - moneyapp_backend
      - moneyapp_frontend
