enum EmitterEvents {
  SET_AUTH_USER = "SET_AUTH_USER",
  LOG_OUT = "LOG_OUT",
  SHOW_LOADING = "SHOW_LOADING",
  SHOW_NOTIFICATION = "SHOW_NOTIFICATION",
  LOAD_NOTIFICATIONS = "LOAD_NOTIFICATIONS",
  RELOAD_ACCOUNTS = "RELOAD_ACCOUNTS",
  SET_NOTIFICATIONS = "SET_NOTIFICATIONS",
}

export default EmitterEvents;
