enum ServerNotificationTypes {
  NEW_TRANSACTION = "NEW_TRANSACTION",
  EMAIL_VERIFIED = "EMAIL_VERIFIED",
  INSUFFICENT_BALANCE = "INSUFFICENT_BALANCE",
  TRANSACTION_ALREADY_COMPLETED = "TRANSACTION_ALREADY_COMPLETED",
  TRANSACTION_FAILED = "TRANSACTION_FAILED",
}

export default ServerNotificationTypes;
